### PR TITLE
Matus krska/gym entity

### PR DESCRIPTION
**Pull request by matus-krska**
Implementation of Gym entity

### CODE REVIEW

**Review by PeterTopor94 — COMMENTED** [review]
Why didn't you check typology for null value in equals method as you did for other attributes? I would expect same comparing approach and "return true;" at the end.

**Comment by matus-krska** [comment]
Typology is an enum so it can be compared with == operator in all cases (e.g. null == Type.WATER returns false)

**Review by PeterTopor94 — COMMENTED** [review]
Fair potint. I approve it then.

**Review by PeterTopor94 — COMMENTED** [review]
I noticed that in equals and hashcode method you refered to class attributes without using "this". Even when there are no other variables with same name, I think you should use it so the code is consistent.

**Review by PeterTopor94 — APPROVED** [review]

**Review by Alkanthor — APPROVED** [review]

**Pull request merged**
