### PR TITLE
renamed methods in badgeDao test to fit with entity class, remove dup…

### PR DESCRIPTION
**Pull request by Alkanthor**
…licite attribute

### CODE REVIEW

**Review by PeterTopor94 — COMMENTED** [review]
PokemonType enum is alredy implemented

**Comment by matus-krska** [comment]
A bit of a mistake commiting empty PokemonType?

**Comment by Alkanthor** [comment]
I dont know, how this happened, never touched that class

**Comment by matus-krska** [comment]
Probably a branch which was not rebased properly agaisnt updated master, or idk...

**Review by matus-krska — APPROVED** [review]
approved

**Pull request merged**
