### PR TITLE
add dependency - lombok library

### PR DESCRIPTION
**Pull request by miroslav14**
pridal som library lombok / @getter a @setter

### CODE REVIEW

**Review by Alkanthor — COMMENTED** [review]
nothing to object

**Review by Alkanthor — APPROVED** [review]
nothing to object

**Comment by matus-krska** [comment]
Yeah go ahead and merge it

**Comment by PeterTopor94** [comment]
Approving change. Merging

**Review by PeterTopor94 — APPROVED** [review]

**Pull request merged**
