### PR TITLE
Roman

### PR DESCRIPTION
**Pull request by Alkanthor**
my assignment

- Pokemon DAO class
- Trainer class
- Badge test class

I based those classes on the model solution, but I expect you to have multiple reservations

### CODE REVIEW

**Comment by matus-krska** [comment]
In pom.xml of Data module, there probably shouldn't be dependency on:
<artifactId>eshop-persistence</artifactId> of the teachers' project

**Comment by matus-krska** [comment]
Also maybe put your full name to @Author tag

**Comment by matus-krska** [comment]
I think there is a small mistake in PokemonDAO, method findByOwner. IF you expect pokemon to have attribute owner of type Trainer, there should be p.owner.id in query not just p.owner

EDIT: my bad you put the whole trainer in parameter ownerid. I'm not sure whether that will work. I'm used to seeing something like p.owner.id, and then setting the parameter to t.getId()

**Comment by PeterTopor94** [comment]
I also think that it would be better to refer to trainer via id not objet itself.

However, we can approve this change and merge it to avoid duplicate work and to get access to created classes as I have no objection to the rest of the code.

**Review by PeterTopor94 — APPROVED** [review]

**Review by matus-krska — APPROVED** [review]

**Pull request merged**
