### PR TITLE
Matus krska/trainer dao

### PR DESCRIPTION
**Pull request by matus-krska**
Implementation of TrainerDAO
Creation of ApplicationContext for Data (in memory database...)

### CODE REVIEW

**Review by miroslav14 — COMMENTED** [review]
TrainerDaoImpl the last method (findByNameAndSurname) will probably need return statement

**Review by miroslav14 — APPROVED** [review]
For me ok.

**Review by PeterTopor94 — COMMENTED** [review]
You are missing update method in DAO implementation.

**Comment by matus-krska** [comment]
In the teachers' example, there is no update, only create, which persists the object, but for clarity's sake i agree with you. I will add it.

**Review by PeterTopor94 — APPROVED** [review]
I approve changes

**Review by smilek1234 — APPROVED** [review]

**Pull request merged**
