### PR TITLE
added pokemons property to trainer, fixed bugs in PokemonDao

### PR DESCRIPTION
**Pull request by Alkanthor**

### CODE REVIEW

**Review by matus-krska — APPROVED** [review]

**Review by PeterTopor94 — COMMENTED** [review]
Why did you replace getSingleResult with detResultList?

**Comment by matus-krska** [comment]
Yeah, there are some replacement which were not needed, only those methods that return List<> must have getResultList() inside them.

**Comment by Alkanthor** [comment]
@matus-krska I replaced it in all methods as they all return List, do you see a method, which returns a single item?

**Comment by matus-krska** [comment]
@Alkanthor For example findById
EDIT: my bad, the files were cut in a strange way, everything seems allright

**Comment by Alkanthor** [comment]
@matus-krska 
Yes, but there is no _getResultList()_

**Pull request merged**
