### PR TITLE
Lubos

### PR DESCRIPTION
**Pull request by smilek1234**
Added Badge Entity, BadgeDao, BadgeDaoImpl & GymDaoTest.

### CODE REVIEW

**Review by PeterTopor94 — COMMENTED** [review]
In Badge class use "this.attr" every time you refer to class attribute so the code is consistant

**Review by PeterTopor94 — COMMENTED** [review]
In getOwners return unmodifiable list so it is not possible to add owners witout usnig addOwner

**Review by PeterTopor94 — COMMENTED** [review]
There is missing implemetation of update method. Is it intended ?

**Review by PeterTopor94 — COMMENTED** [review]
In Badge constructor assignment "this.owners = owners" might not work as paramater owner is temporary and at the end of methot will be deleted do this.owner will lose that refference. I recommend creating new list from the parameter like "this.owners = new ArrayList<Trainer>(owners)"

**Review by PeterTopor94 — APPROVED** [review]
I approve changes

**Review by PeterTopor94 — APPROVED** [review]

**Review by matus-krska — APPROVED** [review]

**Review by miroslav14 — COMMENTED** [review]
In the class BadgeDao are missing JavaDoc annotation on some obj.

**Review by PeterTopor94 — APPROVED** [review]

**Review by miroslav14 — APPROVED** [review]

**Review by matus-krska — APPROVED** [review]

**Pull request merged**
